#
# Copyright 2019, Intel Corporation
#
# 'recipe' for Docker to build an RPM
#

# Pull base image
FROM opensuse/leap:15.1
MAINTAINER Brian J. Murrell <brian.murrell@intel.com>

# use same UID as host and default value of 1000 if not specified
ARG UID=1000

# Add build user (to keep rpmbuild happy)
ENV USER build
ENV PASSWD build
RUN useradd -u $UID -ms /bin/bash $USER
RUN groupadd -g $UID $USER
RUN echo "$USER:$PASSWD" | chpasswd

# Install basic tools
RUN zypper --non-interactive update
RUN zypper --non-interactive install build

# install dependencies (these are broken/lacking Requires: in some RPMs)
# we should not have to install these; this is a packaging bug
RUN zypper --non-interactive install perl-XML-Parser perl-libwww-perl
